"""Добавить presentation_id в Slide

Revision ID: 678c58f4eef8
Revises: 
Create Date: 2024-12-14 01:40:02.526097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '678c58f4eef8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slides', schema=None) as batch_op:
        batch_op.add_column(sa.Column('presentation_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'presentations', ['presentation_id'], ['presentation_id'])
        batch_op.drop_column('presentation_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slides', schema=None) as batch_op:
        batch_op.add_column(sa.Column('presentation_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('presentation_id')

    # ### end Alembic commands ###
