"""add

Revision ID: 69436db00946
Revises: 678c58f4eef8
Create Date: 2024-12-14 01:52:11.361756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69436db00946'
down_revision = '678c58f4eef8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presentations', schema=None) as batch_op:
        batch_op.alter_column('google_slide_id',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_constraint('presentations_created_by_fkey', type_='foreignkey')

    with op.batch_alter_table('slides', schema=None) as batch_op:
        batch_op.alter_column('presentation_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint('slides_added_by_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slides', schema=None) as batch_op:
        batch_op.create_foreign_key('slides_added_by_fkey', 'users', ['added_by'], ['user_id'])
        batch_op.alter_column('presentation_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('presentations', schema=None) as batch_op:
        batch_op.create_foreign_key('presentations_created_by_fkey', 'users', ['created_by'], ['user_id'])
        batch_op.alter_column('google_slide_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
