"""Remove presentation_name from slides and fix backrefs

Revision ID: ffa7f66996da
Revises: 69436db00946
Create Date: 2024-12-14 02:52:26.060486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffa7f66996da'
down_revision = '69436db00946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('presentations', schema=None) as batch_op:
        batch_op.alter_column('google_slide_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['user_id'])

    with op.batch_alter_table('slides', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['added_by'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('slides', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('presentations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('google_slide_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
